export const topics = [
  "Renewable Energy",
  "Climate Change",
  "Deforestation",
  "Global Warming",
  "Clean Water Access",
  "Electric Vehicles",
  "Wildlife Conservation",
  "Pollution Control",
  "Plastic Ban",
  "Ocean Protection",
  "Air Quality Improvement",
  "Recycling Culture",
  "Eco-Friendly Technology",
  "Artificial Intelligence",
  "Machine Learning",
  "Digital India",
  "Smart Cities",
  "Robotics",
  "Automation and Jobs",
  "Cybersecurity",
  "The Internet of Things",
  "Space Exploration",
  "Virtual Reality(VR)",
  "Online Education",
  "Skill-Based Learning",
  "Importance of Reading",
  "Future of Education",
  "Ethical Education",
  "Coding in Schools",
  "Student Mental Health",
  "Digital Classrooms",
  "Gender Equality",
  "Freedom of Speech",
  "Human Rights",
  "Social Media Impact",
  "Privacy and Data Protection",
  "Poverty Eradication",
  "Child Labour",
  "Mental Health Awareness",
  "Domestic Violence",
  "Self-Discipline",
  "Power of Positivity",
  "Time Management",
  "Leadership",
  "Importance of Kindness",
  "Overcoming Failure",
  "Self-Confidence",
  "Teamwork",
  "Goal Setting",
  "Work-Life Balance",
  "Renewable Fuels",
  "3D Printing",
  "Smart Healthcare",
  "Digital Privacy",
  "Make in India",
  "Atmanirbhar Bharat",
  "Swachh Bharat Abhiyan",
  "Beti Bachao Beti Padhao",
  "Skill India",
  "Start-up India",
  "Digital Literacy",
  "Women Empowerment in India",
  "Youth in Nation Building",
  "Rural Development",
  "Globalization",
  "World Peace",
  "International Cooperation",
  "Global Economy",
  "Pandemic Preparedness",
  "Sustainable Development Goals",
  "Humanitarian Aid",
  "War and Ethics",
  "Global Health Equity",
  "Cultural Diversity",
  "Power of Empathy",
  "Value of Truth",
  "Unity in Diversity",
];
